Repository grapefruit13/yourdentity, pull requests merged in 2025-10, with the labels that each got.

#40 [FEAT#35] 커뮤니티/스토어 API 및 기타 설정
  be/functions/.eslintrc.js
  be/functions/index.js
  be/functions/package.json
  be/functions/pnpm-lock.yaml
  be/functions/src/config/database.js
  be/functions/src/config/swagger.js
  be/functions/src/controllers/commentController.js
  be/functions/src/controllers/communityController.js
  be/functions/src/controllers/gatheringController.js
  be/functions/src/controllers/imageController.js
  be/functions/src/controllers/missionController.js
  be/functions/src/controllers/routineController.js
  be/functions/src/controllers/storeController.js
  be/functions/src/controllers/tmiController.js
  be/functions/src/controllers/userController.js
  be/functions/src/middleware/errorHandler.js
  be/functions/src/middleware/logger.js
  be/functions/src/routes/comments.js
  be/functions/src/routes/communities.js
  be/functions/src/routes/gatherings.js
  be/functions/src/routes/images.js
  be/functions/src/routes/missions.js
  be/functions/src/routes/routines.js
  be/functions/src/routes/store.js
  be/functions/src/routes/tmi.js
  be/functions/src/routes/users.js
  be/functions/src/scripts/createFirestoreCollections.js
  be/functions/src/services/firestoreService.js
  be/functions/src/services/imgbbService.js
  be/functions/src/utils/helpers.js
  firebase.json
Labels: BE, ✨ feature

#44 [Feat#41] 카카오 소셜 로그인 및 이메일 회원가입 구현
  be/functions/.gitignore
  be/functions/index.js
  be/functions/package-lock.json
  be/functions/package.json
  be/functions/pnpm-lock.yaml
  be/functions/src/config/database.js
  be/functions/src/config/swagger.js
  be/functions/src/controllers/imageController.js
  be/functions/src/controllers/missionController.js
  be/functions/src/controllers/userController.js
  be/functions/src/middleware/authGuard.js
  be/functions/src/middleware/errorHandler.js
  be/functions/src/routes/images.js
  be/functions/src/routes/missions.js
  be/functions/src/routes/users.js
  be/functions/src/services/firestoreService.js
  be/functions/src/services/imgbbService.js
  be/functions/src/services/missionService.js
  be/functions/src/services/userService.js
  be/functions/src/triggers/authTrigger.js
  be/functions/src/utils/helpers.js
  fe/src/app/(auth)/email-login/page.tsx
  fe/src/app/(auth)/layout.tsx
  fe/src/app/(auth)/signup/page.tsx
  fe/src/app/(main)/layout.tsx
  fe/src/app/api/send-notification/route.ts
  fe/src/app/globals.css
  fe/src/app/layout.tsx
  fe/src/app/manifest.ts
  fe/src/app/page.tsx
  fe/src/lib/auth.ts
  fe/src/lib/firebase.ts
  firebase.json
Labels: BE, ✨ feature

#42 [FEAT38] 마이페이지와 설정 페이지 구현
  fe/.husky/pre-commit
  fe/package.json
  fe/pnpm-lock.yaml
  fe/src/app/(main)/layout.tsx
  fe/src/app/(main)/my-page/page.tsx
  fe/src/app/(main)/settings/page.tsx
  fe/src/app/api/auth/logout/route.ts
  fe/src/app/api/send-notification/route.ts
  fe/src/app/api/user/delete/route.ts
  fe/src/components/community/CommunityDetail.tsx
  fe/src/components/community/PostFeed.tsx
  fe/src/components/community/UserImageCarousel.tsx
  fe/src/components/my-page/ActionButtons.tsx
  fe/src/components/my-page/LogoutModal.tsx
  fe/src/components/my-page/PointsCard.tsx
  fe/src/components/my-page/ProfileCard.tsx
  fe/src/components/my-page/SettingsSection.tsx
Labels: FE, ✨ feature

#54 [Fix#53] Firestore 서비스 임포트 방식 및 페이지네이션 메서드 통일
  be/functions/src/controllers/commentController.js
  be/functions/src/controllers/communityController.js
  be/functions/src/controllers/gatheringController.js
  be/functions/src/controllers/routineController.js
  be/functions/src/controllers/storeController.js
  be/functions/src/controllers/tmiController.js
  be/functions/src/services/firestoreService.js
Labels: BE, 🐛 bug

#57 [FEAT#56] 로컬 인증 토큰 발급 스크립트 추가
  be/functions/package.json
  be/functions/src/scripts/getIdToken.js
Labels: BE, ➕ optional
